### ISSUE TITLE
关于 tool.ShanTou.University

### ISSUE THREAD

**Issue by ShanTou-U** [Momu02/PhoenixTool#1]
您好，我们是 [ST.U](https://shantou.university) 的开发者，ST.U 的域名是 [ShanTou.University](https://shantou.university)，致力于创建一个开源公开的 Online STU。

看到您开发和维护的 PheonixTool，我们很想在 ST.U 为它开设一个专门的子域名，可以用来提供服务，也可以用来发布相关的信息，不知道您是否同意。

我们目前的想法是： 您提供一个 ip 地址，然后我们会将 tool.ShanTou.University 解析过去，然后您可以利用这个子域名按您想要的方式提供服务，我们充分信任您。

请随时和我们联系，可以通过 [dev@ShanTou.University](mailto:dev@ShanTou.University) 或者 [ST.U GitHub 组织](https://github.com/ShanTouUniversity) 找到我们。

（PS: 添加 DNS 解析后，您可以在自己的服务器上用 [caddy](https://caddyserver.com/) 之类的工具申请ssl证书）

另外需要说明的是，这是完全志愿的工作，域名和服务器都是我们自己在掏腰包；我们可能无法为您提供报酬。

**Comment by Momu02** [comment]
尊敬的 ST.U 的开发者：
	你好，你的来信我已收到！
	关于PheonixTool安卓版的项目开发基本已接近停更，且PheonixTool主要功能是让校内学生更加方便快捷的使用校内各种资源，目前没有关于服务器的需求（所有功能都可在软件内实现），软件也没有其他的联网需要，所以PheonixTool项目本身没有任何服务器后台支持。该安卓项目停更后我便转到了小程序开发，目前也已开发出体验版（尚未上线，如需体验可搜索STUTool公众号查看），不过同样没有为其配置服务器，均是尽力在其前端完成数据交互。目前我技术尚浅，关于小程序开发也是初识皮毛，我对于你们的来信表示感激，如果以后有能力需要会联系你们的。
	另外我曾经同样对你们网站上的学业指南项目感兴趣，以前曾想过设计一个公开文档，里面可涵盖关于目前新生入学直至毕业就业的一些信息，帮助我校学生打破信息差。不过该设想所需成本精力巨大，个人难以实现，遂放弃。
	如果你在未来有需要STUTool团队帮助的地方（比如帮助宣传），也可以与我联系。

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Momu02/STUTool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月7日(星期六) 下午3:36
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Momu02/STUTool] 关于 tool.ShanTou.University (Issue #1)





 
您好，我们是 ST.U 的开发者，ST.U 的域名是 ShanTou.University，致力于创建一个开源公开的 Online STU。
 
看到您开发和维护的 PheonixTool，我们很想在 ST.U 为它开设一个专门的子域名，可以用来提供服务，也可以用来发布相关的信息，不知道您是否同意。
 
我们目前的想法是： 您提供一个 ip 地址，然后我们会将 tool.ShanTou.University 解析过去，然后您可以利用这个子域名按您想要的方式提供服务，我们充分信任您。
 
请随时和我们联系，可以通过 ***@***.*** 或者 ST.U GitHub 组织 找到我们。
 
（PS: 添加 DNS 解析后，您可以在自己的服务器上用 caddy 之类的工具申请ssl证书）
 
另外需要说明的是，这是完全志愿的工作，域名和服务器都是我们自己在掏腰包；我们可能无法为您提供报酬。

**Comment by ShanTou-U** [comment]
谢谢您的回复，PheonixTool 是难得的实用工具，ST.U 向您的尝试致敬。同样筚路蓝缕、创业维艰，共勉。
